language: go

go:
  - "1.13"

matrix:
  include:
    - name: "Postgres 11"
      env:
        - PGDB=11
    - name: "Postgres 10"
      env:
        - PGDB=10
        - RELEASE=true
    - name: "Postgres 9.6"
      env:
       - PGDB=9.6

env:
  global:
    - GO111MODULE=on

services:
  - redis-server

before_install:
  - sudo -E service postgresql stop 9.2
  - sudo -E service postgresql stop 9.3
  - sudo -E service postgresql stop 9.4
  - sudo -E service postgresql stop 9.5
  - sudo -E service postgresql stop 9.6
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PGDB postgresql-client-$PGDB
  - sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
  - sudo -E service postgresql restart $PGDB
  # setup redis
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379

before_script:
  - psql -U postgres -c "CREATE USER courier WITH PASSWORD 'courier';"
  - psql -U postgres -c "ALTER ROLE courier WITH SUPERUSER;"
  - psql -U postgres -c "CREATE DATABASE courier_test;"
  - psql -U postgres -d courier_test -f backends/rapidpro/schema.sql

script:
  - go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/courier/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.text

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $RELEASE = true  
